server:
  port: 3000


spring:
  # 데이터베이스 설정 들여쓰기 제거 후 작성 시작
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      show-sql: true # 실행하는 SQL을 콘솔에 출력
      format_sql: true # 실행되는 sql의 들여쓰기 및 줄 개행
      use_sql_comments: true
      #dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

